version: '2'

services:
  app:
    build:
      image: 239402555961.dkr.ecr.eu-central-1.amazonaws.com/brain/brain
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_NEO4J_URI=http://neo4j:7474

  neo4j:
    image: "neo4j"
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"

  aws_dockercfg:
    image: codeship/aws-ecr-dockercfg-generator
    add_docker: true
    encrypted_env_file: aws.env.encrypted
