version: '2'
services:
  knowledge:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_NEO4J_URI=http://neo4j:7474
  neo4j:
    image: "neo4j"
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"